/*
 * Complete the 'anagram' function below.
 *
 * The function is expected to return an INTEGER.
 * The function accepts STRING s as parameter.
 */

function anagram(s) {
    let hasEvenLength = s.length % 2 == 0
    
    if (!hasEvenLength) return -1

    let subString_1 = s.slice(0, s.length / 2)
    let subString_2 = s.slice(s.length / 2)

    let amountOfNumToChange = 0

    for (let i = 0; i < subString_1.length; i++) {

        if (!subString_2.includes(subString_1[i])) {
            
            amountOfNumToChange++
        }
        subString_2 = subString_2.replace(subString_1[i], '')
    }

    return amountOfNumToChange
}

console.log(anagram('dojlxwppwzbypgnokhgeudmlrgngpqeshpdenuvkwwilfyzphiublgoeodkduoxdgajtxedtcoghogxvqtwdbmhpputliqqqtzkqfplkdrrrzqoplksmyccqwxbgpuxkvhcbynnefevexkuiwovxqznmyqtnksygbajzowdvabzxntilidiacxpaokpycpgdspeilidolcnyyvjiyukcrzehjwilloqfevnrfsfqxtoxozhptrrnrywcueqhtgnzdcqivyyurorhoywjpoyiovlibbpwjcvnhoxcmwwfmpmcnjmezmnnjavldmhmrfbytzchxamjpymejaikoxxyxujcjspaxqaqrcxoclytkmxvmfgaffyeajhlcylzqlsippwtbwmnijkwqqxvyxaajhllfymvlefawctzyfmjqyfgpecncennlaasympjtvjpxeqxlegbcohrslgwpvjcvlutakcthnkgradcemfgcnauaitsgcubqrxqdblkpvqgxvldjqllfngiwzaedwftncjqgucvrsdqqqtzhhlourwssywvveriicbozdlqypjofenolyfirbcjabhvfyfpcgebmrskgdaohnetojdhlfrngaknardcyjemayyjbyzindddnglamcnuezkeqpgqakccicllakuqqztdgeduisqmraqhpzyrjcuuffhhsdxkdrnjxsdgktsbwlknkkfvpzrugzbacbkfuxqrpvxbrscnfparzhooggkphoplrctlbjcrfcuwwzlbonupvigdqsuzgmlxogkppniwrdunchqsvkhsupxliskqevoudajtnsrgxotzvlrsvamqqkdyenokleeofnjufdberwdoiwhfxtxpfapjqdtbkxrrlbnseqxxnclxbseyocptcedsjyvvwnmjqadwqctfheeizjinlxgpdlkmkfkiuwtmywipbbwiibqhkyuxxcmaqwoaeykavdnvbvmczjkhmcqwcmtzqhzggqimosmlxzhbxtdyeqhquxoxljwbrykzoslcnzqkzxnysrwzjfpdcgcppzqixahnvuriuhuvgivzbtymyprcvurltjvsmfhhbyrvglsmvnlyglkebcgyyzlrjhlvosepqvlwiflgtyezkrgntolroxkzgxwupajhxwghcrnxrsybjeoetcxjzjifgebxgkgdjmmnfakxuiafprlktitutbbzhcynoeszremyeyvajyfypqkiadetefsnjsazxuzqynofmmfxklxzdhjeknzqusffmfejzdzzroefckemxbnckyiwniohctmoasybwxapnhwptadqdsupqdlflzonuabuvzxrzxioeegxejpjekyunjcakqngrocoqzfrwnfdrlcxxsibegxtrztdqgjjwlxomefktlnmysjxmtyqzylszevrmgaktzzffgpytfksxvploqbpqohpsehgkjqdlrkqycrrhblgzbrntudjimycrhibtaheurwstnlcrxkqadftxichxcjoktrdwyjqshknvvqmuceugjndurnruwhgsylozwerdoeylwmgzsahcqkwhxpdwwlouwetskmyatwlrltsfwzhmmfvluzhsmxpjbkdlxblsazjnscsobccnhyzeziwlgnwjycxvdknflwuganucpzryzseabdljqkuomtlreyzpxtvzisdztvyspcssffbyrymfryxxyynxtkxceabzxbrpglhnrllkjyqaypyynnwgzvkgxmfxnzmtkthdesopsgqsvqrkfpqembmjpsietuadqhjwbxmwdeqawhkbychkfuwuoebjbbmtivrlufjzjabhjliiosuvosqezrnaubvczmptszvdbwnkkxuaprvfjnjigwkayfcxuusovptwoggyedytuvzdjkmphyqheugaoaojqhheqqeutepnzosibgakfqrlkzlbzbmpkuvakbuffkuhampdtrnahglufyxfzjwlfumrviyduskxfbaatoaculyclvhkhfxmzlgxuecqzmnepqgkggnctleehnqotncuzktvrvlqjbwzrcjxkybdkghttzjoonjpyekrayjjzfksjwrtusweyfzsgiguwrkwwwpyuyjvfunosejmzhtxmsrudaqbtazpzoptozptvejnlszkzujnpbjsdztwcuobkduycltxsckdwmnxgwmvzvpcukbwepxosumxhhuzjhehvtebsszrnowkzxgfmgugcidlqanbhrlclpfdkewxvshurqzfyvmaeplwpyxysicdaiikogjjbrfsjhyhckhibuetvetnmwsogcyuikgjblekuctzocjpwqktuegiaaxgexcnhiykwcwsgprurdkqtujnasvauuizslobvmmrrkkxcdstgelzavmbpkdjemiyxwaslomcaybcbtykzjjagydxkghosrprqrmbhyfhwimxekjdvtfetibdritjcidszpvgncqlkckoouulpzpikrldbeodprxoisxvupihttxhprsetimfbziedwiuqhlyakwwzefszdboutspdgugfcllbvfrcqreandbuittlukiqexvlucqyndzklsmbktezwhtebpsxzcpdblovphuekvoxqazctfbrmvypmsplugoxtftiopmymawcdxeyeiqsfqirizcefsbzxujllwmyykcdjjcpruhymrpuqtyynzxlwgyjemjfymijxmyqigouzfoqyoolqnymvzvanfhmtpxqewgmewjdbxvbojoeynquonwbudpnsnfylnlrluwmtspjdenetfyhtuipxafrpmqcadtlzraulpertrvmztvupgjogofxdxzdauqblswzicqdvlsugnoxvalbqsatqzwstpuhhsgrwwxrjpmreaoaczdttemjfjczayihsobomyfvptovwcxyddrwjeiopmppmxyenzuzzbwovkmrmjrrmjqxpymekbvwbtcovwquxmluxznliffxqvuftildmgznzddwzttyigthfisppzofujmptxsfdtsfwybxtwwbcrijzdzrcnwzyjosijxmestdswaltypxpzhrcgihvgiwryoahnoohjrzfrnascahbhagpkpmtzikxwmhmcvtlmttfivxkvhnchttukgnjoxjnmqzolucxpxexschojvssqomduzokzxxlnybatfzicegxgpnrmfjfvyipxyawwzjlylmtqlbvpjsxbfqnmcuiaczxbzwzbhkbswulkxgbjabkhrzttubtydtbcrafyngtlcevamxloyvvrwolqsgpvbszutftinmtqspsgodwmarfwhqnbzeycwyxrfqzuetkykegyhemjvrgekvglzenxekrjcqgilsixxqvgujqrdywntcauintnakyedenoxxmuojckvscyqynlcnfkabxclyhocufbttxheaszswxlumywzggchgeseljihokbhhkljeneampuzpsyvbccjhvpsgxcujddtnqcudguqxrrnlrkmunvbkkvqkxmvcpoqhtklbgdzxwojnyxhnvixfgnrfzniqdyywklysqzsmnbznahbvradzqufrjninnijxthrjgjvvmulndoivonweibwtoggbosahbsqkbnhqjsdngnkxbgdlizewhnavhaeiuwsyjcoturgdesafydsifxhmmhktjodelwcuaqpujxxppzxqfpykofyamivwxzcixeexwurftrujsrbxhzjxhiyvstrpsvzrzeoxaictzzetsfrbhazokxjdsdunyueaatxabcvcdcvvhoxqrwedvqgptdetxjtxetzhvwlyyitixsyqqftlvadodhhcsdbwwafrysrxbmhyffovkjjfjmvovfsoitmgvuzumqtncanhhdfunobyczpxehnobcuywtsilnynplxxrctgsueutvtzdjpgljehezrpmpfcdcbueucyqgumepnhydpjotstukkjbpleroaxkcvclpopfcyfhnrvijodvbmxqzdkpejbihdtwukdyilfxcagnrljszikanuprgscnvvjpipnqauoevwrmhcgimqianzttrvgmrpezgtriohmldgxmkdwxtexgdqzwmhlfxpgfkzqyhejmkibvnxsjcrrhjtevarczgkfskxrtbcfmngjagdjiwbrfuxbuofwwqbpcyivbmcnzlycrdnbzqsfksihgpdffgujgeehshxusxwjbjkaaehmwpvffakmggwomcwejvydsuotgywifdubvsgcssqbyopkrnpcingdkuwqvuaaaudxmmzheridgxpznebvujaggzybtydtuiqhurozjwcrvtqiatgwdicjhambarwuzpdugrtrpxinqaxqufmxoqivsuyslvpmksgsmzkdyusrvqhpxwonowljqjbdgspqlyjzzvcypxpmpybmwpclnnufyxifsavfygexdixvfmhunljjclwqasvysgdkgbpgjvfnddilrrhecsqffmvfhsezyjlgmcowxulcztnqmvxppnwvbraklgjkswseyhaxblacgnstkpkaegvizxskgewyarcbydybqydxoxsapcctkzdjxwtdasbcjfdjkekbcpasmutbyvxivaruwmzyecbphgyskivpxvhmpannykxvlopjaoihqlyzrxtehothjatadipdtmygcppffzoxkmwelqitebcqdvsgdklywlgbawgfxueigboutwnzxrraokjtuwssiytiwzqwvugexuyqqnqnehpstalnxfihgbpedhaacgezacsqpifvrxnlzbayikfoovttettgayiccatukapbxfoxirvqdbfryakcvelvetygvtaftqirxzqfqlxvoenoextadgxhbxowqqbkildfkvmcikyxolntkivqosxpqnlieoumcxumsgrdspchcpcoyzeoreejrrsximkkmg'))

